

services:
  postgres:
    image: postgres:17
    container_name: postgres_reserva_aviones
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reserva_aviones
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: reserva_aviones
      DB_HOST: postgres
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules  # evita sobrescribir los node_modules del contenedor
    command: npm run dev
    restart: unless-stopped

volumes:
  db_data:
