version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_reserva_aviones
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reserva_aviones
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .. 
      dockerfile: docker/Dockerfile 
    container_name: app_container
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: reserva_aviones
      DB_HOST: postgres
    volumes:
      - ..:/app
    ports:
      - "5000:5000"

volumes:
  db_data: